In [1]:
import numpy as np

# Function: Sigmoid activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Function: Derivative of sigmoid (for backpropagation)
def sigmoid_derivative(x):
    return x * (1 - x)

# Setting random seed (optional, for reproducibility)
np.random.seed(42)

# ----- STEP 1: Initialize Parameters -----

# Define input size (N) and hidden layer sizes
N = 4           # Number of binary inputs
hidden1_size = 5  # Number of neurons in Hidden Layer 1
hidden2_size = 3  # Number of neurons in Hidden Layer 2
output_size = 1   # Single binary output

# Random input data (binary: 0 or 1)
X = np.random.randint(0, 2, (10, N))  # 10 samples

# Random target outputs (binary)
y = np.random.randint(0, 2, (10, output_size))

# Random initialization of weights and biases
W1 = np.random.rand(N, hidden1_size)
b1 = np.random.rand(1, hidden1_size)

W2 = np.random.rand(hidden1_size, hidden2_size)
b2 = np.random.rand(1, hidden2_size)

W3 = np.random.rand(hidden2_size, output_size)
b3 = np.random.rand(1, output_size)

# Learning rate
lr = 0.1

# ----- STEP 2: Training Loop -----
steps = 1000  # Number of steps

for step in range(steps):

    # ---- Forward Propagation ----
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    z3 = np.dot(a2, W3) + b3
    output = sigmoid(z3)

    # ---- Compute Error ----
    error = y - output

    # ---- Backward Propagation ----
    d_output = error * sigmoid_derivative(output)

    d_hidden2 = d_output.dot(W3.T) * sigmoid_derivative(a2)

    d_hidden1 = d_hidden2.dot(W2.T) * sigmoid_derivative(a1)

    # ---- Update Weights and Biases ----
    W3 += a2.T.dot(d_output) * lr
    b3 += np.sum(d_output, axis=0, keepdims=True) * lr

    W2 += a1.T.dot(d_hidden2) * lr
    b2 += np.sum(d_hidden2, axis=0, keepdims=True) * lr

    W1 += X.T.dot(d_hidden1) * lr
    b1 += np.sum(d_hidden1, axis=0, keepdims=True) * lr

# ----- STEP 3: Final Output -----

print("Final Weight Matrix W1 (Input -> Hidden Layer 1):\n", W1)
print("\nFinal Bias b1 (Hidden Layer 1):\n", b1)

print("\nFinal Weight Matrix W2 (Hidden Layer 1 -> Hidden Layer 2):\n", W2)
print("\nFinal Bias b2 (Hidden Layer 2):\n", b2)

print("\nFinal Weight Matrix W3 (Hidden Layer 2 -> Output):\n", W3)
print("\nFinal Bias b3 (Output Layer):\n", b3)

print(f"\nTotal Number of Steps = {steps}")


Final Weight Matrix W1 (Input -> Hidden Layer 1):
 [[ 0.78920421  0.64426527  0.53269575  0.61298804 -0.00264436]
 [-1.18207288 -1.4302054   0.09495968  0.91961712  1.21020501]
 [ 1.7670974   1.87588059  0.08268574  0.70361356  0.23610271]
 [ 0.35403574  0.85994209  0.03569779  0.91519493  0.2057797 ]]

Final Bias b1 (Hidden Layer 1):
 [[-0.36722904 -0.27791772  0.54433455  0.53543241  0.24174695]]

Final Weight Matrix W2 (Hidden Layer 1 -> Hidden Layer 2):
 [[ 0.9988761   1.86783728  1.16407199]
 [ 0.88463499  2.22671423  1.39647357]
 [ 0.19033707 -0.14570102 -0.40704613]
 [ 0.46609532 -0.29391841 -0.37621352]
 [ 0.98322576 -0.75544444 -0.50131997]]

Final Bias b2 (Hidden Layer 2):
 [[ 0.72580433 -1.08461383 -0.11202814]]

Final Weight Matrix W3 (Hidden Layer 2 -> Output):
 [[-0.58932882]
 [ 3.15859511]
 [ 1.61912494]]

Final Bias b3 (Output Layer):
 [[-1.17015659]]

Total Number of Steps = 1000
